feat: add MiniAppDirectJump
cinit/QAuxiliary pull request #1032
Opened 2024-06-17 15:04 UTC by Xunflash

# feat: add MiniAppDirectJump

## Description

长按小程序/分享卡片增加直接打开APP的菜单项，省去打开卡顿的小程序/网页的步骤（暂时仅支持哔哩哔哩）
## Issues Fixed or Closed by This PR
（（回滚失误不小心把pr给close了，顺便直接把嵌套的if改了，另外其他两个问题是从qa里面抄的代码，应该问题不大吧（？
## Check List

- [x] I have tested the changes and verified that they work and don't break anything(as well as I can manage) or drop the support for previous versions.
- [x] I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

2024-06-18 04:56 UTC, qwq233 requested changes

2024-06-18 04:56 UTC, qwq233 commented on app/src/main/java/top/xunflash/hook/MiniAppDirectJump.kt
> +    }
```suggestion
private fun expandShortUrl(shortUrl: String): String? = CoroutineScope(Dispatchers.IO).future {
        val connection = (URL(shortUrl).openConnection() as HttpURLConnection).apply {
            instanceFollowRedirects = false
            connectTimeout = 10000
            readTimeout = 10000
        }
        val result = connection.getHeaderField("Location")
        connection.disconnect()
        result
    }.get()
```

2024-06-18 04:58 UTC, qwq233 commented on app/src/main/java/top/xunflash/hook/MiniAppDirectJump.kt
> +    }
一般来讲这可能有点阻塞，你看需求改

2024-06-18 04:59 UTC, qwq233 commented on app/src/main/java/top/xunflash/hook/MiniAppDirectJump.kt
> +    }
哦 这个是说你哪个什么expandShortUrl的 括的地方错了

2024-06-18 17:32 UTC, Xunflash commented on app/src/main/java/top/xunflash/hook/MiniAppDirectJump.kt
> +    }
已修改

2024-06-19 10:27 UTC, qwq233 commented
你改了测试过没有的，主要我写的这些随便写的，没测试的

2024-06-19 17:48 UTC, Xunflash commented
> 你改了测试过没有的，主要我写的这些随便写的，没测试的

测试了，没问题的

2024-06-19 17:48 UTC, qwq233 approved these changes

2024-06-19 17:48 UTC, merged