misc: update easter egg emojis
cinit/QAuxiliary pull request #222
Opened 2022-11-14 04:11 UTC by canyie

# Update easter egg emojis

(Not tested, CI can't run for my fork)

## Description

- The transgender emoji is also common and the transgender flag emoji includes it
- The "fish cake with swirl" emoji is also widely used among Chinese MtFs/MtXs

## Issues Fixed or Closed by This PR
N/A

## Check List

- [ ] I have tested the changes and verified that they work and don't break anything(as well as I can manage) or drop the support for previous versions.
- [x] I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

2022-11-14 04:15 UTC, NextAlone commented
**喵**

2022-11-14 04:18 UTC, Cryolitia requested changes
🏳‍⚧作为一个有独立Unicode编码的符号是不需要将其编码拆分成两部分再分别判断的，是你的设备无法打出跨性别旗吗？

2022-11-14 04:18 UTC, Cryolitia commented on app/src/main/java/io/github/qauxv/fragment/SettingsMainFragment.kt
> +            if ((buddyName?.contains("\u26A7\uFE0F") == true || buddyName?.contains("\uD83C\uDF65") == true) &&
```suggestion
            if ((buddyName?.contains("\uD83C\uDFF3\uFE0F\u200D\u26A7\uFE0F") == true || buddyName?.contains("\u26A7\uFE0F") == true || buddyName?.contains("\uD83C\uDF65") == true) &&
```

2022-11-14 04:18 UTC, Cryolitia commented on app/src/main/java/me/singleneuron/util/EasterEggsForTheNonexistent.kt
> +        arrayOf("\u26A7\uFE0F", "\uD38C\uDF65", "mtf", "mtx", "ftm", "ftx", "transgender") to forSuBanXia,
```suggestion
        arrayOf("\uD83C\uDFF3\uFE0F\u200D\u26A7\uFE0F", "\u26A7\uFE0F", "\uD38C\uDF65", "mtf", "mtx", "ftm", "ftx", "transgender") to forSuBanXia,
```

2022-11-14 04:58 UTC, canyie commented on app/src/main/java/io/github/qauxv/fragment/SettingsMainFragment.kt
> +            if ((buddyName?.contains("\u26A7\uFE0F") == true || buddyName?.contains("\uD83C\uDF65") == true) &&
跨性别旗🏳‍⚧实际上是由一个白旗🏳️+一个[零宽连字符](https://emojipedia.org/zero-width-joiner/)+一个跨性别符号⚧️组成的，只判断跨性别符号理论上也可以识别到跨性别旗

2022-11-15 16:42 UTC, Cryolitia approved these changes
![image](https://user-images.githubusercontent.com/23723294/201976651-69e49677-6c39-474c-b794-79d0d7a7af7f.png)
这个地方没问题了，可以准备合并。
为什么设置为draft？

2022-11-20 10:07 UTC, merged