feat: Remove a tip when open a blocked group
cinit/QAuxiliary pull request #774
Opened 2024-01-26 07:03 UTC by MoonLeeeaf

# 移除“修改消息设置，实时接收或收入群助手”

## Description

实在没有IDE能调试，还请各位大佬帮我测试下

该方法针对 Tim 3.5.1

针对内容如下图

![Screenshot_20240126_145902](https://github.com/cinit/QAuxiliary/assets/150461955/f0445ebf-6574-4f08-ad5d-e51fa2ca072e)
![Screenshot_20240126_145853](https://github.com/cinit/QAuxiliary/assets/150461955/a5af9cde-68fa-40e2-8589-4a4c32655e5f)

## Issues Fixed or Closed by This PR

#667 

## Check List

- [ ] I have tested the changes and verified that they work and don't break anything(as well as I can manage) or drop the support for previous versions.
- [ ] I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

2024-01-26 07:14 UTC, cinit requested changes
建议修改一下包名，撤销 gradlew mode 的改动，另外 commit 建议 [GPG 签名](https://docs.github.com/cn/github/authenticating-to-github/managing-commit-signature-verification)

2024-01-26 07:14 UTC, cinit commented on app/src/main/java/github/moonleeeaf/hook/RemoveBlockedGroupTipHook.java
> +package github.moonleeeaf.hook;
包名的命名：如果没有域名的话，可以用 GitHub pages 的用户域名，如 `io.github.moonleeeaf`  而不是 `github.moonleeeaf`, 对应此次可以为 `io.github.moonleeeaf.hook`.

2024-01-26 07:14 UTC, cinit commented on gradlew
gradlew 的 mode (100755) 请不要改动。

2024-01-26 16:04 UTC, MoonLeeeaf commented
同步好了，还请Review以确保不会出错👌
不知道我的GPG签名有没有生效，我没法查看我所有的commit list  :-(

2024-01-26 16:13 UTC, MoonLeeeaf reviewed
已根据要求进行修改（[修改后的commit](https://github.com/cinit/QAuxiliary/pull/774/commits/17c500cb547e7d9ccbe034307aeeafd3ec97e7fb)），感谢大佬指点
我发现我的GPG签名用了Github的只读邮箱居然还是unverified，现在我不知道要怎么重新签名了:-(

2024-01-26 16:13 UTC, MoonLeeeaf commented on gradlew
属于Android媒体文件目录的毛病，在我的fork已经恢复755了

2024-01-26 16:13 UTC, MoonLeeeaf commented on app/src/main/java/github/moonleeeaf/hook/RemoveBlockedGroupTipHook.java
> +package github.moonleeeaf.hook;
已遵循该方法命名，感谢指点:-)

2024-01-27 05:16 UTC, cinit commented
1. 你的 GPG 公钥要上传到 GitHub
2. 你 commit 的邮箱要和你 GPG id 邮箱一致

2024-01-27 05:47 UTC, MoonLeeeaf commented
请问现在我该怎么样才能重新签名 想着重新 git commit -s -m "" && git push 没成反倒把原来的密钥删了QWQ

2024-01-27 17:07 UTC, closed without merging